import os

# Set environment variables you want below here for development, or within the docker deployment:
# -----------------------------------------------------------------------------------------------

# Serializer class overrides. Uncomment and edit the location to point to your class override
# os.environ['OBSERVATIONS_SUMMARY_SERIALIZER'] = 'observation_portal.observations.serializers.SummarySerializer'
# os.environ['OBSERVATIONS_CONFIGURATIONSTATUS_SERIALIZER'] = 'observation_portal.observations.serializers.ConfigurationStatusSerializer'
# os.environ['OBSERVATIONS_TARGET_SERIALIZER'] = 'observation_portal.observations.serializers.ObservationTargetSerializer'
# os.environ['OBSERVATIONS_CONFIGURATION_SERIALIZER'] = 'observation_portal.observations.serializers.ObservationConfigurationSerializer'
# os.environ['OBSERVATIONS_REQUEST_SERIALIZER'] = 'observation_portal.observations.serializers.ObserveRequestSerializer'
# os.environ['OBSERVATIONS_REQUESTGROUP_SERIALIZER'] = 'observation_portal.observations.serializers.ObserveRequestGroupSerializer'
# os.environ['OBSERVATIONS_SCHEDULE_SERIALIZER'] = 'observation_portal.observations.serializers.ScheduleSerializer'
# os.environ['OBSERVATIONS_OBSERVATION_SERIALIZER'] = 'observation_portal.observations.serializers.ObservationSerializer'
# os.environ['OBSERVATIONS_CANCEL_SERIALIZER'] = 'observation_portal.observations.serializers.CancelObservationsSerializer'
# os.environ['REQUESTGROUPS_CADENCE_SERIALIZER'] = 'observation_portal.requestgroups.serializers.CadenceSerializer'
# os.environ['REQUESTGROUPS_CADENCEREQUEST_SERIALIZER'] = 'observation_portal.requestgroups.serializers.CadenceRequestSerializer'
# os.environ['REQUESTGROUPS_CONSTRAINTS_SERIALIZER'] = 'observation_portal.requestgroups.serializers.ConstraintsSerializer'
# os.environ['REQUESTGROUPS_REGIONOFINTEREST_SERIALIZER'] = 'observation_portal.requestgroups.serializers.RegionOfInterestSerializer'
# os.environ['REQUESTGROUPS_INSTRUMENTCONFIG_SERIALIZER'] = 'observation_portal.requestgroups.serializers.InstrumentConfigSerializer'
# os.environ['REQUESTGROUPS_ACQUISITIONCONFIG_SERIALIZER'] = 'observation_portal.requestgroups.serializers.AcquisitionConfigSerializer'
# os.environ['REQUESTGROUPS_GUIDINGCONFIG_SERIALIZER'] = 'observation_portal.requestgroups.serializers.GuidingConfigSerializer'
# os.environ['REQUESTGROUPS_TARGET_SERIALIZER'] = 'observation_portal.requestgroups.serializers.TargetSerializer'
# os.environ['REQUESTGROUPS_CONFIGURATION_SERIALIZER'] = 'observation_portal.requestgroups.serializers.ConfigurationSerializer'
# os.environ['REQUESTGROUPS_LOCATION_SERIALIZER'] = 'observation_portal.requestgroups.serializers.LocationSerializer'
# os.environ['REQUESTGROUPS_WINDOW_SERIALIZER'] = 'observation_portal.requestgroups.serializers.WindowSerializer'
# os.environ['REQUESTGROUPS_REQUEST_SERIALIZER'] = 'observation_portal.requestgroups.serializers.RequestSerializer'
# os.environ['REQUESTGROUPS_REQUESTGROUP_SERIALIZER'] = 'observation_portal.requestgroups.serializers.RequestGroupSerializer'
# os.environ['REQUESTGROUPS_DRAFTREQUESTGROUP_SERIALIZER'] = 'observation_portal.requestgroups.serializers.DraftRequestGroupSerializer'
# os.environ['PROPOSALS_PROPOSAL_SERIALIZER'] = 'observation_portal.proposals.serializers.ProposalSerializer'
# os.environ['PROPOSALS_PROPOSALINVITE_SERIALIZER'] = 'observation_portal.proposals.serializers.ProposalInviteSerializer'
# os.environ['PROPOSALS_SEMESTER_SERIALIZER'] = 'observation_portal.proposals.serializers.SemesterSerialzer'
# os.environ['PROPOSALS_MEMBERSHIP_SERIALIZER'] = 'observation_portal.proposals.serializers.MembershipSerializer'
# os.environ['PROPOSALS_PROPOSALNOTIFICATION_SERIALIZER'] = 'observation_portal.proposals.serializers.ProposalNotificationSerializer'
# os.environ['PROPOSALS_TIMELIMIT_SERIALIZER'] = 'observation_portal.proposals.serializers.TimeLimitSerializer'
# os.environ['ACCOUNTS_PROFILE_SERIALIZER'] = 'observation_portal.accounts.serializers.ProfileSerializer'
# os.environ['ACCOUNTS_USER_SERIALIZER'] = 'observation_portal.accounts.serializers.UserSerializer'
# os.environ['ACCOUNTS_ACCOUNTREMOVAL_SERIALIZER'] = 'observation_portal.accounts.serializers.AccountRemovalSerializer'
# os.environ['SCIAPPLICATIONS_CALL_SERIALIZER'] = 'observation_portal.sciapplications.serializers.CallSerializer'
# os.environ['SCIAPPLICATIONS_SCIENCEAPPLICATION_SERIALIZER'] = 'observation_portal.sciapplications.serializers.ScienceApplicationSerializer'
