"""
Django settings for observation_portal project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

# Import local environment variable overrides for serializer classes, or specify within docker deployment
from env_overrides import *

# Import all base project settings, then overwrite as needed
from observation_portal.settings import *

# Override whatever settings from the settings.py below here:
# ------------------------------------------------------------